# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Arey

repo_name: codito/arey
repo_url: https://github.com/codito/arey

nav:
  - Getting Started: 'index.md'
  - Guides:
    - Llama models: 'llama.md'
    - OpenAI: 'openai.md'
  - Configuration: 'config.md'
  - Contribute: 'contribute.md'

theme:
  name: material
  features:
    - content.code.copy
  icon:
    admonition:
      windows: simple/windows
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
