name: linux

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        id: rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy, llvm-tools-preview
      - name: Install LLVM Coverage
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Cache test data
        uses: actions/cache@v3
        with:
          path: target/arey-test-data
          key: ${{ runner.os }}-arey-test-data
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Format check
        run: cargo fmt --all -- --check
      - name: Lint with Clippy
        run: cargo clippy --all-targets --tests --benches -- -D warnings
      - name: Code coverage
        run: cargo llvm-cov --codecov --output-path coverage.json
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: codito/arey
